/* Generated By:JJTree&JavaCC: Do not edit this line. CalculatorConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface CalculatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 4;
  /** RegularExpression Id. */
  int CROSS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int STAR = 7;
  /** RegularExpression Id. */
  int DASH = 8;
  /** RegularExpression Id. */
  int LP = 9;
  /** RegularExpression Id. */
  int RP = 10;
  /** RegularExpression Id. */
  int LF = 11;
  /** RegularExpression Id. */
  int MINUS_LP = 12;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<INTEGER>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"\\n\"",
    "\"-(\"",
  };

}
